[phases.setup]
nixPkgs = ["python312", "curl"]

[phases.install]
cmds = [
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "/root/.local/bin/uv venv /opt/venv",
    "/root/.local/bin/uv pip install --python /opt/venv/bin/python -r requirements.txt"
]

[start]
cmd = "bash -c 'chmod +x /app/docker-entrypoint.sh && /app/docker-entrypoint.sh'"
