[phases.setup]
nixPkgs = ["python312", "curl"]

[phases.install]
cmds = [
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "export PATH=\"/root/.local/bin:$PATH\"",
    "uv pip install --system -r requirements.txt"
]

[start]
cmd = "/docker-entrypoint.sh"
